# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_auto_20160105_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
