# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_query_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='snapshot',
            field=models.BooleanField(default=True, help_text=b'Include in snapshot task (if enabled)'),
        ),
    ]
