# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20170614_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name=b'file name'),
        ),
    ]
