# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_auto_20170626_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
