# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 11:18
from __future__ import unicode_literals

from django.db import migrations, models


def update_bucket_field(apps, schema_editor):
    Query = apps.get_model('explorer', 'Query')
    db_alias = schema_editor.connection.alias
    Query.objects.using(db_alias).filter(
        bucket__isnull=True
    ).update(bucket='')


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_query_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='bucket',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.RunPython(update_bucket_field, migrations.RunPython.noop),
    ]
