# Generated by Django 5.0.4 on 2024-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0021_alter_databaseconnection_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='upload_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
