# Generated by Django 5.0.4 on 2024-08-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0024_auto_20240803_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='database_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.databaseconnection'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='database_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.databaseconnection'),
        ),
    ]
