# Generated by Django 5.0.4 on 2024-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0026_tabledescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='few_shot',
            field=models.BooleanField(default=False, help_text='Will be included as a good example of SQL in assistant queries that use relevant tables'),
        ),
    ]
